name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "tesy"
database_id = "477a450f-f578-4a0b-8f9d-4719bce05c68"

[version_metadata]
binding = "CF_VERSION_METADATA"
